apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-axle-weight-operator
  description: Axle weigh operator
  annotations:
    gitlab.com/project-id: '22737057'
spec:
  type: service
  lifecycle: production
  owner: group:hun
  system: backend
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - axle-weight-api